Add httpEndpoint field in Kafka Topic datasource
pulumi/pulumi-confluentcloud pull request #185
Opened 2023-08-24 17:35 UTC by rquitales

2023-08-24 21:02 UTC, iwahbe requested changes
This is very similar to what caused us problems in with `aws.rds.Instance`. Could we remove the patch all-together and apply a similar solution to https://github.com/pulumi/pulumi-aws/pull/2686 (keeping all of our code in `resources.go`).

This way there won't be any unintended interactions within the upstream provider.

2023-08-25 17:34 UTC, iwahbe approved these changes
I'm approving to remove the "(requested changes)" from my review, but I would like a second pair of eyes before I merge.

2023-08-25 18:16 UTC, guineveresaenger approved these changes
Looks good to me, thank you!

I have a personal preference to using the plain string as a lookup key rather than assigning to a const but it's definitely not a blocker 😄

2023-08-25 18:16 UTC, guineveresaenger commented on provider/resources.go
> +						return config, fmt.Errorf(`Cannot specify both "httpEndpoint" and "restEndpoint"` +
super nitty, feel fee to ignore: since we're defining these as `const`s, let's use them here too.
```suggestion
						return config, fmt.Errorf(`Cannot specify both %s and %s` + ...`, httpEndpoint, restEndpoint
```

2023-08-25 18:16 UTC, guineveresaenger commented on provider/resources.go
> +					tfbridge.GetLogger(ctx).Warn(`"httpEndpoint" is deprecated, use "restEndpoint" instead.`)
same here

2023-08-25 18:32 UTC, merged